### ISSUE TITLE
FormBuilderDropdown does not support multiple selections, nor does it support customization of the drop-down option component. Have you considered extending a FormBuilderDropdownButton2 (an extension of the DropdownButton2 component) to achieve the above functions?

### ISSUE THREAD

**Issue by liuhll** [flutter-form-builder-ecosystem/flutter_form_builder#1420] opened 2024-08-17 15:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.4.1

### What you'd like to happen

```Markdown
I hope to expand a form component that supports multiple selections in a drop-down list and custom drop-down list formbuilder widget.
```

**Comment by deandreamatias** [comment] 2024-08-17 20:10
Duplicate of https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/issues/112

**Closed by deandreamatias** 2024-08-17 20:10 UTC
Labels: enhancement
